/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef _EDITOR_AUTHORS_H
#define _EDITOR_AUTHORS_H
static const char *dev_founders[] = {
	"Juan Linietsky (reduz)",
	"Ariel Manzur (punto-)",
	0
};
static const char *dev_lead[] = {
	"Juan Linietsky (reduz)",
	0
};
static const char *dev_manager[] = {
	"R\303\251mi Verschelde (akien-mga)",
	0
};
static const char *dev_names[] = {
	"Alexander Holland (AlexHolly)",
	"Alexey Velikiy (jonyrock)",
	"Alket Rexhepi (alketii)",
	"Andrea Catania (AndreaCatania)",
	"Andreas Haas (Hinsbart)",
	"Andy Moss (MillionOstrich)",
	"Anton Yabchinskiy (a12n)",
	"Aren Villanueva (kurikaesu)",
	"Ariel Manzur (punto-)",
	"Bastiaan Olij (BastiaanOlij)",
	"Ben Brookshire (sheepandshepherd)",
	"Benjamin (Nallebeorn)",
	"Bernard Liebl (poke1024)",
	"B\305\202a\305\274ej Szczygie\305\202 (zaps166)",
	"Bojidar Marinov (bojidar-bg)",
	"bruvzg",
	"Carl Olsson (not-surt)",
	"Dana Olson (adolson)",
	"Daniel J. Ramirez (djrm)",
	"Dmitry Koteroff (Krakean)",
	"Emmanuel Leblond (touilleMan)",
	"est31",
	"Fabio Alessandrelli (Faless)",
	"Ferenc Arn (tagcup)",
	"Franklin Sobrinho (TheHX)",
	"Geequlim",
	"Gen (dbsGen)",
	"George Marques (vnen)",
	"Gerrit Gro\303\237kopf (Grosskopf)",
	"Gilles Roudiere (groud)",
	"Guilherme Felipe de C. G. da Silva (guilhermefelipecgs)",
	"Hein-Pieter van Braam (hpvb)",
	"Hiroshi Ogawa (hi-ogawa)",
	"Hubert Jarosz (Marqin)",
	"Hugo Locurcio (Calinou)",
	"Ian Bishop (ianb96)",
	"Ibrahn Sahir (ibrahn)",
	"Ignacio Etcheverry (neikeq)",
	"Indah Sylvia (ISylvox)",
	"J08nY",
	"Jakub Grzesik (kubecz3k)",
	"J\303\251r\303\264me GULLY (Nutriz)",
	"JFonS",
	"Johan Manuel (29jm)",
	"Joshua Grams (JoshuaGrams)",
	"Juan Linietsky (reduz)",
	"Julian Murgia (StraToN)",
	"Justo Delgado (mrcdk)",
	"Kelly Thomas (KellyThomas)",
	"Kostadin Damyanov (Max-Might)",
	"Leon Krause (eska014)",
	"m4nu3lf",
	"Marcelo Fernandez (marcelofg55)",
	"Marc Gilleron (Zylann)",
	"Mariano Javier Suligoy (MarianoGnu)",
	"Mario Schlack (hurikhan)",
	"Martin Sjursen (binbitten)",
	"marynate",
	"Masoud BH (masoudbh3)",
	"Matthias H\303\266lzl (hoelzl)",
	"Max Hilbrunner (mhilbrunner)",
	"Michael Alexsander Silva Dias (YeldhamDev)",
	"mrezai",
	"Nathan Warden (NathanWarden)",
	"Nuno Donato (nunodonato)",
	"Ovnuniarchos",
	"Pascal Richter (ShyRed)",
	"Patrick (firefly2442)",
	"Paul Batty (Paulb23)",
	"Paul Joannon (paulloz)",
	"Pawel Kowal (pkowal1982)",
	"Pedro J. Est\303\251banez (RandomShaper)",
	"Pieter-Jan Briers (PJB3005)",
	"Poommetee Ketson (Noshyaar)",
	"Przemys\305\202aw Go\305\202\304\205b (n-pigeon)",
	"Ralf H\303\266lzemer (rollenrolm)",
	"Ramesh Ravone (RameshRavone)",
	"Ray Koopa (RayKoopa)",
	"R\303\251mi Verschelde (akien-mga)",
	"Roberto F. Arroyo (robfram)",
	"romulox-x",
	"rraallvv",
	"Ruslan Mustakov (endragor)",
	"Saniko (sanikoyes)",
	"SaracenOne",
	"sersoong",
	"Theo Hallenius (TheoXD)",
	"Thomas Herzog (karroffel)",
	"Timo (toger5)",
	"Vinzenz Feenstra (vinzenz)",
	"\353\260\225\355\225\234\354\226\274 (volzhs)",
	"V. Vamsi Krishna (vkbsb)",
	"Wilhem Barbier (nounoursheureux)",
	"Will Nations (willnationsdev)",
	"Wilson E. Alvarez (Rubonnek)",
	"Xavier Cho (mysticfall)",
	"yg2f (SuperUserNameMan)",
	"Yuri Roubinski (Chaosus)",
	"Zher Huei Lee (leezh)",
	"ZuBsPaCe",
	"\320\224\320\274\320\270\321\202\321\200\320\270\320\271 \320\241\320\260\320\273\321\214\320\275\320\270\320\272\320\276\320\262 (DmitriySalnikov)",
	"Diogo Carneiro (Gamevolutions)",
	0
};
#endif
